import { Party } from '@c7/ledger';
import { jwtDecode, JwtPayload } from 'jwt-decode';

// NOTE: These types are placeholders for the actual types generated by `dpm codegen-js`.
// In a real project, you would import these from a path like `../daml/codegen/dist/lib`.
// For this example, we define them inline to show their expected structure.
// Let's assume the module path is `Marketplace.Listing` and `Marketplace.UsageAgreement`.
declare module Codegen {
  export namespace Marketplace.Listing {
    // Corresponds to the `DatasetListing` template payload
    export interface DatasetListing {
      provider: Party;
      title: string;
      description: string;
      price: string; // Daml Decimal is a string in JSON
      currency: string;
      revenueShareAgreement: string; // ContractId RevenueShare
    }
    // Represents an active contract on the ledger
    export interface Instance {
      contractId: string;
      templateId: string;
      payload: DatasetListing;
    }
    // Static property on the generated type object
    export const templateId = "Marketplace.Listing:DatasetListing";
  }

  export namespace Marketplace.UsageAgreement {
    export interface UsageAgreement {
      provider: Party;
      consumer: Party;
      datasetTitle: string;
      licenseGrantDate: string; // Daml Time is string in JSON
      accessUrl: string; // The off-chain location of the data
    }
    export interface Instance {
      contractId: string;
      templateId: string;
      payload: UsageAgreement;
    }
    export const templateId = "Marketplace.UsageAgreement:UsageAgreement";
  }
}

// Type alias for convenience
type DatasetListingInstance = Codegen.Marketplace.Listing.Instance;
type UsageAgreementInstance = Codegen.Marketplace.UsageAgreement.Instance;

/**
 * A common JWT payload structure for Canton/Daml applications, where the
 * party and ledger ID are included in a custom namespace.
 */
interface DamlJWTPayload extends JwtPayload {
  party: Party;
  ledgerId: string;
}

const ledgerUrl = process.env.REACT_APP_LEDGER_URL || 'http://localhost:7575';
const jsonApiHeaders = (token: string) => ({
  'Authorization': `Bearer ${token}`,
  'Content-Type': 'application/json',
});

/**
 * Decodes a JWT and extracts the party identifier.
 * @param token The JWT token string.
 * @returns The party identifier (string).
 * @throws An error if the token is invalid or does not contain a party.
 */
const getParty = (token: string): Party => {
  const decoded = jwtDecode<DamlJWTPayload>(token);
  if (!decoded.party) {
    throw new Error('Party not found in JWT token.');
  }
  return decoded.party;
};

/**
 * Handles the response from the JSON API, throwing a formatted error on failure.
 * @param response The raw fetch response.
 * @returns The JSON parsed body of the response.
 */
const handleResponse = async (response: Response) => {
  if (!response.ok) {
    const errorText = await response.text();
    console.error('Ledger API request failed:', errorText);
    throw new Error(`Ledger API Error: ${response.status} - ${errorText}`);
  }
  return response.json();
};


/**
 * Fetches all active dataset listings from the ledger visible to the user.
 * @param token The authentication token for the user.
 * @returns A promise that resolves to an array of active DatasetListing contracts.
 */
const fetchListings = async (token: string): Promise<DatasetListingInstance[]> => {
  const response = await fetch(`${ledgerUrl}/v1/query`, {
    method: 'POST',
    headers: jsonApiHeaders(token),
    body: JSON.stringify({
      templateIds: [Codegen.Marketplace.Listing.templateId]
    }),
  });

  const { result } = await handleResponse(response);
  return result as DatasetListingInstance[];
};

/**
 * Exercises the 'Purchase' choice on a DatasetListing contract.
 * @param token The authentication token for the buyer.
 * @param listingCid The contract ID of the DatasetListing to purchase.
 * @returns A promise that resolves when the purchase is complete.
 */
const purchaseDataset = async (token:string, listingCid: string): Promise<void> => {
  const consumer = getParty(token);

  const body = {
    templateId: Codegen.Marketplace.Listing.templateId,
    contractId: listingCid,
    choice: 'Purchase',
    argument: {
      consumer,
    },
  };

  const response = await fetch(`${ledgerUrl}/v1/exercise`, {
    method: 'POST',
    headers: jsonApiHeaders(token),
    body: JSON.stringify(body),
  });

  await handleResponse(response);
};

/**
 * Fetches all active UsageAgreement contracts for the current user.
 * The JSON API automatically scopes queries to contracts visible to the token's party.
 * @param token The authentication token for the user.
 * @returns A promise that resolves to an array of active UsageAgreement contracts.
 */
const fetchMyAgreements = async (token: string): Promise<UsageAgreementInstance[]> => {
  const response = await fetch(`${ledgerUrl}/v1/query`, {
    method: 'POST',
    headers: jsonApiHeaders(token),
    body: JSON.stringify({
      templateIds: [Codegen.Marketplace.UsageAgreement.templateId],
    }),
  });

  const { result } = await handleResponse(response);
  return result as UsageAgreementInstance[];
};

/**
 * Creates a new DatasetListing contract on the ledger.
 * @param token The authentication token for the data provider.
 * @param payload The data for the new listing, excluding the 'provider' field.
 * @returns A promise that resolves when the listing is created.
 */
const createListing = async (
  token: string,
  payload: Omit<Codegen.Marketplace.Listing.DatasetListing, 'provider'>
): Promise<void> => {
  const provider = getParty(token);

  const body = {
    templateId: Codegen.Marketplace.Listing.templateId,
    payload: {
      ...payload,
      provider: provider,
    },
  };

  const response = await fetch(`${ledgerUrl}/v1/create`, {
    method: 'POST',
    headers: jsonApiHeaders(token),
    body: JSON.stringify(body),
  });

  await handleResponse(response);
};

/**
 * A service object that encapsulates all interactions with the marketplace on the ledger.
 */
export const marketplaceService = {
  getParty,
  fetchListings,
  purchaseDataset,
  fetchMyAgreements,
  createListing,
};